language: c

sudo: required

compiler:
  - gcc

before_script:
  - wget https://github.com/maximilianvoss/csafestring/archive/v1.5.tar.gz -O /tmp/csafestring.tar.gz
  - tar -xvzf /tmp/csafestring.tar.gz -C /tmp
  - (cd /tmp/csafestring-1.5; cmake -G "Unix Makefiles" && sudo make install)
  
script:
  - cmake -G "Unix Makefiles" && make && make test