language: c

sudo: required

compiler:
  - gcc

before_script:
  - CSAFESTRING_VERSION=1.8; export CSAFESTRING_VERSION
  
  - wget https://github.com/maximilianvoss/csafestring/archive/v${CSAFESTRING_VERSION}.tar.gz -O /tmp/csafestring.tar.gz
  - tar -xvzf /tmp/csafestring.tar.gz -C /tmp
  - (cd /tmp/csafestring-${CSAFESTRING_VERSION}; cmake -DCMAKE_C_FLAGS="-DEXPERIMENTAL_SIZING" -G "Unix Makefiles" && sudo make install)
  
script:
  - cmake -G "Unix Makefiles" && make && make test
