language: c

sudo: required

compiler:
  - gcc

before_script:
  - wget https://github.com/maximilianvoss/csafestring/archive/v1.4.tar.gz -O /tmp/csafestring.tar.gz
  - tar -xvzf /tmp/csafestring.tar.gz -C /tmp
  - cmake /tmp/csafestring-1.4 -G "Unix Makefiles"
  - sudo make install -C /tmp/csafestring-1.4
  
script:
  - cmake -G "Unix Makefiles" && make